### PR TITLE
Throw BookError exception if book already exists in list

### PR DESCRIPTION
**Pull request by ajsmash7**
@minneapolis-edu code now raises BookError if exact_match returns > 0. This solves issue #4 

Please let me know if you find any errors, or if is ok to commit.

### CODE REVIEW

**Comment by claraj** [comment]
@ajsmash7 looks good.  @johnascott1 can you resolve the conflict and merge? Let me know if any problems.

**Comment by johnascott1** [comment]
SO, GIthub is telling me that lines 16-24 in bookstore.py is causing the conflict, but I'm not quite sure how. Here's a screenshot.[cid:b9e05671-b933-42cd-a375-879437f95bf0]

________________________________

**Comment by claraj** [comment]
Can't see screenshot, let's fix it in before class tomorrow?

**Comment by johnascott1** [comment]
Okay, I think I fixed it.

**Comment by johnascott1** [comment]
Okay, it's fixed

**Pull request merged**
